# Generated by Django 3.0.2 on 2020-01-12 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_registereventusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereventusers',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
