# Generated by Django 3.0.2 on 2020-01-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200112_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='description',
        ),
    ]
