# Generated by Django 3.0.2 on 2020-01-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_star_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='department',
            field=models.CharField(blank=True, choices=[('cse', 'Comeputer Science'), ('ee', 'Electrical'), ('ece', 'Electronic and Communication'), ('mech', 'Mechanical'), ('bca', 'BCA'), ('mca', 'MCA'), ('hm', 'Hotel Management')], max_length=120, null=True),
        ),
    ]
