# Generated by Django 3.0.2 on 2020-01-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200114_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='department',
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
