# Generated by Django 3.0.2 on 2020-01-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200115_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='categories',
            new_name='category',
        ),
    ]
