# Generated by Django 3.0.2 on 2020-01-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereventusers',
            name='registeration_id',
            field=models.CharField(default='adav123test', max_length=15),
        ),
    ]
