# Generated by Django 3.0.2 on 2020-01-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_registereventusers_registeration_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereventusers',
            old_name='registeration_id',
            new_name='registration_id',
        ),
    ]
