# Generated by Django 3.0.2 on 2020-01-12 14:39

from django.db import migrations, models
import organizers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=organizers.models.upload_location)),
                ('name', models.CharField(max_length=150)),
                ('typ', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyCordinators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=organizers.models.upload_location)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCordinators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=organizers.models.upload_location)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
