# Generated by Django 3.0.2 on 2020-01-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultycordinators',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
